CREATE TABLE users (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username VARCHAR(20) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE authentication (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	CONSTRAINT fk_user_auth
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);